#!/bin/sh

cp tempinput input.1
../../gadget/source/gadget -l -i input.1 -opt optinfofile -nowarnings

cp params.out input.2
../../gadget/source/gadget -l -i input.2 -opt optinfofile -nowarnings

cp params.out input.3
../../gadget/source/gadget -l -i input.3 -opt optinfofile -nowarnings

cp params.out input.4
../../gadget/source/gadget -l -i input.4 -opt optinfofile -nowarnings

cp params.out input.5
../../gadget/source/gadget -l -i input.5 -opt optinfofile -nowarnings

cp params.out input.6
../../gadget/source/gadget -l -i input.6 -opt optinfofile -nowarnings

cp params.out input.7
../../gadget/source/gadget -l -i input.7 -opt optinfofile -nowarnings

cp params.out input.8
../../gadget/source/gadget -l -i input.8 -opt optinfofile -nowarnings

cp params.out input.9
../../gadget/source/gadget -l -i input.9 -opt optinfofile -nowarnings

cp params.out input.10
../../gadget/source/gadget -l -i input.10 -opt optinfofile -nowarnings


cp params.out  final.params
cp params.out tempinput

../../gadget/source/gadget -s -i final.params -o lik.out
